[Setup]
; device mac
Mac = XX:XX:XX:XX:XX
; device type
Type = EB3A
; device serial
Serial = XXXXXXX
; update interval
Interval = 5
; Standby current consumption
StandbyCurrent = 3.6
; debug
debug = false

